### ISSUE TITLE
Performance of recorder.stop()

### ISSUE THREAD

**Issue by gjvengelen** [prasanaworld/puppeteer-screen-recorder#8] opened 2021-05-17 17:40 UTC
- **I'm submitting a question about how to use this project

- **Summary**
Hi,
I'm currently trying to implement this package, I have it working and the results are quite promising.
But the performance of recorder.stop() is quite low, I did a bit of debugging and saw that it's when `this.isScreenCaptureEnded = await this.streamWriter.stop();` is being called. Sometimes it takes up to 30 seconds to stop the recorder.

I'm not sure if it's my implementation, can you tell me if this is normal behavior?

```
public async close(): Promise<void> {
        if(this.recorderOptions.recorderOn){
            await this.stopRecorder()
        }
        return (await this.activePage).browser().close()
    }

public async stopRecorder(): Promise<void>{
        await this.recorder.stop();
    }
```

**Comment by prasanaworld** [comment] 2021-05-17 18:27
Hi gjvengelen,

This is probably because of the `FFmpeg` library which combines stream of the image received from the chrome-dev tool protocol and writes it as a .mp4 video player. 

Is it possible to share some information like how long are you trying to record video and at what frame rate.  

But I believe it should not yield for 30 seconds unless there are other performance issues that block the chrome-dev tool to send the last image stream.

**Comment by gjvengelen** [comment] 2021-05-18 07:07
Hi Prasana,
Thnx for the quick response.
The length of the video is about 15 seconds, I timed the time it takes to stop `streamWriter()` that is 20 seconds almost always.
The config I'm using is:
'''
const config = {
            followNewTab: true,
            fps: 25,
            videoFrame: {
              width: 1024,
              height: 768,
            },
            aspectRatio: '4:3',
          };
'''
Do you need anything else?

**Comment by prasanaworld** [comment] 2021-09-25 20:49
Hi @gjvengelen,

As soon as the stop method is invoked. The collected stream would be queued and eventually it takes  bit more time to write those into physical file.  

This is expected, But 20 more seconds to stop seems bit strange to me.

Could you please share your system configuration under which your experiencing this behaviour. Also please ensure the folder/path you trying to write has required permission or space. 

Also, It would be great, if you could you reproduce this issue with a minimal example. so that I can take a look.

**Comment by prasanaworld** [comment] 2022-08-29 18:10
Closing this issue, since no active discussion are made.

**Closed by prasanaworld** 2022-08-29 18:10 UTC
Labels: question

**Comment by LittleBearXD** [comment] 2024-10-11 06:49
> Hi @gjvengelen,
> 
> As soon as the stop method is invoked. The collected stream would be queued and eventually it takes bit more time to write those into physical file.
> 
> This is expected, But 20 more seconds to stop seems bit strange to me.
> 
> Could you please share your system configuration under which your experiencing this behaviour. Also please ensure the folder/path you trying to write has required permission or space.
> 
> Also, It would be great, if you could you reproduce this issue with a minimal example. so that I can take a look.

 `videoPixelFormat = 'yuva420p'
            videoCodec = 'libvpx-vp9'
          ideOutputOptions = ['-auto-alt-ref 0']; 
          '.webm'`
            when i record transparent video, recorder.stop() use 13secods
