### ISSUE TITLE
Laggy videos

### ISSUE THREAD

**Issue by xRealNeon** [prasanaworld/puppeteer-screen-recorder#6] opened 2021-04-01 21:17 UTC
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I have tried your package but only got very laggy videos back is there anything I can do?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by prasanaworld** [comment] 2021-04-05 05:11
Hi xRealNeon,

Thanks for reaching out. 


Could you please share any sample video which was recorded? Also Please share the following information.

1.  Node Version
2. NPM Version
3. Platform / OS
4. Hardware configuration.

Also, It would be great if you could piece of code that will help to reproduce the issue. Thanks

**Comment by xRealNeon** [comment] 2021-04-05 08:45
Sure! [https://www.youtube.com/watch?v=eslvBd52Qfc](https://www.youtube.com/watch?v=eslvBd52Qfc)
![2021-04-05_10-32](https://user-images.githubusercontent.com/20997346/113554835-35171580-95fa-11eb-9eda-0033427fe3f2.png)

Not the best code just wanted to try this out
```js
const puppeteer = require('puppeteer');
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      '--window-size=1920,1080'
    ]
  });
  const page = await browser.newPage();
  resizeWindow(browser, page, 1920, 1080);
  const Config = {
    followNewTab: true,
    fps: 60,
    videoFrame: {
      width: 1920,
      height: 1080,
    },
    aspectRatio: '16:9',
  };
  const recorder = new PuppeteerScreenRecorder(page, Config);
  
  await page.goto('https://starwarsintrocreator.kassellabs.io/#!/CMXWBXGT3ldfeU0v89pv');
  await page.waitForSelector('.requestInteraction > #requestInteractionButton > div')
  await page.click('.requestInteraction > #requestInteractionButton > div')
  await recorder.start('./output.mp4'); // video must have .mp4 has an extension.
  await page.setDefaultTimeout(2147483647);
  await page.waitForSelector('#downloadButton', {visible: true});
  await recorder.stop();
  await browser.close();
})();

// From Stackoverflow
async function resizeWindow(browser, page, width, height) {
    await page.setViewport({height, width})
  
    // Window frame - probably OS and WM dependent.
    height += 85
    
    // Any tab.
    const targets = await browser._connection.send(
      'Target.getTargets'
    )
  
    // modified code
    const target = targets.targetInfos.filter(t => t.attached === true && t.type === 'page')[0]
    
    // Tab window. 
    const {windowId} = await browser._connection.send(
      'Browser.getWindowForTarget',
      {targetId: target.targetId}
    )
    const {bounds} = await browser._connection.send(
      'Browser.getWindowBounds',
      {windowId}
    )
    
    const resize = async () => {
      await browser._connection.send('Browser.setWindowBounds', {
        bounds: {width: width, height: height},
        windowId
      })
    }
  
    if(bounds.windowState === 'normal') {
      await resize()
    } else {
      await browser._connection.send('Browser.setWindowBounds', {
        bounds: {windowState: 'minimized'},
        windowId
      })
      await resize()
    }
  }
```

**Comment by prasanaworld** [comment] 2021-04-07 08:56
HI xRealNeon,

Thanks for sharing the info. I could reproduce the scenario.

will work to improve the writing of the video frame in optimize manner which will enable the video to render a lot smoother.

**Comment by Uraskin** [comment] 2021-04-08 07:36
Hello! I have same problem.
Write video with this
{
        followNewTab: true,
        fps: 60,
        ffmpeg_Path: null,
        videoFrame: {
            width: 1920,
            height: 1080,
        },
        aspectRatio: '16:9',
}
but result is very laggy

**Comment by prasanaworld** [comment] 2021-05-17 19:02
Closing this defect in favour of the following issue in node puppeteer API.
The  `Page.screencastFrame`  sends the screen frame at the rate of 5 to 20 fps for the pages which have animation/video. 

Since this plugin is based out on puppeteer-core API, closing this defect.

Bug: https://github.com/puppeteer/puppeteer/pull/881

Thread discussion: https://bugs.chromium.org/p/chromium/issues/detail?id=781117

**Closed by prasanaworld** 2021-05-17 19:02 UTC
Labels: bug, enhancement

**Comment by JamesBotterill** [comment] 2021-07-13 20:21
I would update the documentation to make it more publicly known
